# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.30.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.30.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/mete/OneDrive - Bahceşehir Üniversitesi/Projets/sorting_algorithms_visualiser"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/mete/OneDrive - Bahceşehir Üniversitesi/Projets/sorting_algorithms_visualiser/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.30.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.30.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mete/OneDrive - Bahceşehir Üniversitesi/Projets/sorting_algorithms_visualiser/build/CMakeFiles" "/Users/mete/OneDrive - Bahceşehir Üniversitesi/Projets/sorting_algorithms_visualiser/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mete/OneDrive - Bahceşehir Üniversitesi/Projets/sorting_algorithms_visualiser/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named visualiser

# Build rule for target.
visualiser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualiser
.PHONY : visualiser

# fast build rule for target.
visualiser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/build
.PHONY : visualiser/fast

src/BubbleSort.o: src/BubbleSort.cpp.o
.PHONY : src/BubbleSort.o

# target to build an object file
src/BubbleSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/BubbleSort.cpp.o
.PHONY : src/BubbleSort.cpp.o

src/BubbleSort.i: src/BubbleSort.cpp.i
.PHONY : src/BubbleSort.i

# target to preprocess a source file
src/BubbleSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/BubbleSort.cpp.i
.PHONY : src/BubbleSort.cpp.i

src/BubbleSort.s: src/BubbleSort.cpp.s
.PHONY : src/BubbleSort.s

# target to generate assembly for a file
src/BubbleSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/BubbleSort.cpp.s
.PHONY : src/BubbleSort.cpp.s

src/GnomeSort.o: src/GnomeSort.cpp.o
.PHONY : src/GnomeSort.o

# target to build an object file
src/GnomeSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/GnomeSort.cpp.o
.PHONY : src/GnomeSort.cpp.o

src/GnomeSort.i: src/GnomeSort.cpp.i
.PHONY : src/GnomeSort.i

# target to preprocess a source file
src/GnomeSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/GnomeSort.cpp.i
.PHONY : src/GnomeSort.cpp.i

src/GnomeSort.s: src/GnomeSort.cpp.s
.PHONY : src/GnomeSort.s

# target to generate assembly for a file
src/GnomeSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/GnomeSort.cpp.s
.PHONY : src/GnomeSort.cpp.s

src/InsertionSort.o: src/InsertionSort.cpp.o
.PHONY : src/InsertionSort.o

# target to build an object file
src/InsertionSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/InsertionSort.cpp.o
.PHONY : src/InsertionSort.cpp.o

src/InsertionSort.i: src/InsertionSort.cpp.i
.PHONY : src/InsertionSort.i

# target to preprocess a source file
src/InsertionSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/InsertionSort.cpp.i
.PHONY : src/InsertionSort.cpp.i

src/InsertionSort.s: src/InsertionSort.cpp.s
.PHONY : src/InsertionSort.s

# target to generate assembly for a file
src/InsertionSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/InsertionSort.cpp.s
.PHONY : src/InsertionSort.cpp.s

src/KnuthShuffle.o: src/KnuthShuffle.cpp.o
.PHONY : src/KnuthShuffle.o

# target to build an object file
src/KnuthShuffle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/KnuthShuffle.cpp.o
.PHONY : src/KnuthShuffle.cpp.o

src/KnuthShuffle.i: src/KnuthShuffle.cpp.i
.PHONY : src/KnuthShuffle.i

# target to preprocess a source file
src/KnuthShuffle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/KnuthShuffle.cpp.i
.PHONY : src/KnuthShuffle.cpp.i

src/KnuthShuffle.s: src/KnuthShuffle.cpp.s
.PHONY : src/KnuthShuffle.s

# target to generate assembly for a file
src/KnuthShuffle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/KnuthShuffle.cpp.s
.PHONY : src/KnuthShuffle.cpp.s

src/MergeSort.o: src/MergeSort.cpp.o
.PHONY : src/MergeSort.o

# target to build an object file
src/MergeSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/MergeSort.cpp.o
.PHONY : src/MergeSort.cpp.o

src/MergeSort.i: src/MergeSort.cpp.i
.PHONY : src/MergeSort.i

# target to preprocess a source file
src/MergeSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/MergeSort.cpp.i
.PHONY : src/MergeSort.cpp.i

src/MergeSort.s: src/MergeSort.cpp.s
.PHONY : src/MergeSort.s

# target to generate assembly for a file
src/MergeSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/MergeSort.cpp.s
.PHONY : src/MergeSort.cpp.s

src/QuickSort.o: src/QuickSort.cpp.o
.PHONY : src/QuickSort.o

# target to build an object file
src/QuickSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/QuickSort.cpp.o
.PHONY : src/QuickSort.cpp.o

src/QuickSort.i: src/QuickSort.cpp.i
.PHONY : src/QuickSort.i

# target to preprocess a source file
src/QuickSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/QuickSort.cpp.i
.PHONY : src/QuickSort.cpp.i

src/QuickSort.s: src/QuickSort.cpp.s
.PHONY : src/QuickSort.s

# target to generate assembly for a file
src/QuickSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/QuickSort.cpp.s
.PHONY : src/QuickSort.cpp.s

src/SelectionSort.o: src/SelectionSort.cpp.o
.PHONY : src/SelectionSort.o

# target to build an object file
src/SelectionSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/SelectionSort.cpp.o
.PHONY : src/SelectionSort.cpp.o

src/SelectionSort.i: src/SelectionSort.cpp.i
.PHONY : src/SelectionSort.i

# target to preprocess a source file
src/SelectionSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/SelectionSort.cpp.i
.PHONY : src/SelectionSort.cpp.i

src/SelectionSort.s: src/SelectionSort.cpp.s
.PHONY : src/SelectionSort.s

# target to generate assembly for a file
src/SelectionSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/SelectionSort.cpp.s
.PHONY : src/SelectionSort.cpp.s

src/Visualiser.o: src/Visualiser.cpp.o
.PHONY : src/Visualiser.o

# target to build an object file
src/Visualiser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/Visualiser.cpp.o
.PHONY : src/Visualiser.cpp.o

src/Visualiser.i: src/Visualiser.cpp.i
.PHONY : src/Visualiser.i

# target to preprocess a source file
src/Visualiser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/Visualiser.cpp.i
.PHONY : src/Visualiser.cpp.i

src/Visualiser.s: src/Visualiser.cpp.s
.PHONY : src/Visualiser.s

# target to generate assembly for a file
src/Visualiser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/Visualiser.cpp.s
.PHONY : src/Visualiser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualiser.dir/build.make CMakeFiles/visualiser.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... visualiser"
	@echo "... src/BubbleSort.o"
	@echo "... src/BubbleSort.i"
	@echo "... src/BubbleSort.s"
	@echo "... src/GnomeSort.o"
	@echo "... src/GnomeSort.i"
	@echo "... src/GnomeSort.s"
	@echo "... src/InsertionSort.o"
	@echo "... src/InsertionSort.i"
	@echo "... src/InsertionSort.s"
	@echo "... src/KnuthShuffle.o"
	@echo "... src/KnuthShuffle.i"
	@echo "... src/KnuthShuffle.s"
	@echo "... src/MergeSort.o"
	@echo "... src/MergeSort.i"
	@echo "... src/MergeSort.s"
	@echo "... src/QuickSort.o"
	@echo "... src/QuickSort.i"
	@echo "... src/QuickSort.s"
	@echo "... src/SelectionSort.o"
	@echo "... src/SelectionSort.i"
	@echo "... src/SelectionSort.s"
	@echo "... src/Visualiser.o"
	@echo "... src/Visualiser.i"
	@echo "... src/Visualiser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

